services:
  - type: web
    name: openvidreview
    env: node
    buildCommand: ./build.sh
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: PASSWORD
        sync: false
      - key: SECRET
        generateValue: true
      - key: TITLE
        value: OpenVidReview
      - key: CLOUDINARY_CLOUD_NAME
        value: dexvpbvrz
      - key: CLOUDINARY_API_KEY
        value: "653643671545153"
      - key: CLOUDINARY_API_SECRET
        value: "tFhGZNihnQXNhLvRsgmxYpIUJEY"
